# plugin data
name: GameManager
description: This Plugin adds an api for managing multiple (mini-)games on one server.

# build data
main: de.c4vxl.gamemanager.GameManager
version: 1.0-RV-B1                  # 1.0, release, b1
api-version: 1.14                   # plugin supports 1.14+

# author
authors: [ c4vxl ]
website: https://gma.c4vxl.de/


libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.0.0
  - dev.jorel:commandapi-bukkit-kotlin:9.1.0
  - dev.jorel:commandapi-bukkit-shade:9.1.0
